---
- name: Ensure ruby is installed
  apt: pkg=ruby1.9.3 state=present

- name: Ensure bundler gem is installed
  command: gem install bundler

- name: Ensure dependencies are installed with Bundler
  command: bundle install --gemfile=/vagrant/tests-browser/Gemfile

- stat:
    path=/usr/bin/chromedriver
    follow=true
  register: chromedriver

- include: chromedriver.yml
  when: chromedriver.stat.exists == false

- name: Ensure PhantomJS is installed
  apt: pkg=phantomjs state=present

- name: Ensure browsers are installed
  apt: pkg={{ item }} state=installed
  with_items:
    - firefox
    - chromium-browser
