---
# This playbook deploys miRkwood in a Vagrant environment
- hosts: all
  sudo: True
  roles:
    - bioinfo
    - mirkwood
  tasks:
    - name: Create results directory
      file:
        path=/home/vagrant/results
        state=directory
        owner=www-data
        group=www-data

    - name: Make appropriate links for CGI directory
      file:
        src=/vagrant/cgi-bin/
        dest=/bio1/www/cgi-bin/mirkwood
        state=link

    - name: Make appropriate links for HTML directory
      file:
        src=/vagrant/html/
        dest=/bio1/www/html/mirkwood
        state=link

    - name: Prepare results directory
      file:
        src=/home/vagrant/results
        dest=/bio1/www/html/mirkwood/results
        state=link

    - name: Install local RNAstemloop
      file:
        src=/bio1/www/cgi-bin/mirkwood/programs/RNAstemloop-x86_64
        dest=/usr/bin/RNAstemloop
        state=link

    - name: Install local Exonerate
      file:
        src=/bio1/www/cgi-bin/mirkwood/programs/exonerate-2.2.0-x86_64
        dest=/bio1/www/cgi-bin/mirkwood/programs/exonerate
        state=link

    - name: Make links for programs
      file:
        src=/opt/{{ item.path }}
        dest=/bio1/www/cgi-bin/mirkwood/programs/{{ item.dest }}
        state=link
      with_items:
        - { path: 'VARNAv3-91.jar', dest: 'VARNA.jar' }
        - { path: 'miRdup', dest: 'miRdup-1.2' }
