---
# This playbook deploys miRkwood in a Vagrant environment
- hosts: all
  sudo: True
  roles:
    - bioinfo
    - mirkwood
  tasks:
    - name: Create results directory
      file:
        path=/home/vagrant/results
        state=directory
        owner=www-data
        group=www-data

    - name: Prepare results directory
      file:
        src=/home/vagrant/results
        dest=/bio1/www/html/mirkwood/results
        state=link

    - name: Making appropriate links for CGI directory
      file:
        src=/vagrant/cgi-bin/
        dest=/bio1/www/cgi-bin/mirkwood
        state=link

    - name: Making appropriate links for HTML directory
      file:
        src=/vagrant/html/
        dest=/bio1/www/html/mirkwood
        state=link

    - name: Install RNAstemloop
      file:
        src=/bio1/www/cgi-bin/mirkwood/programs/RNAstemloop-x86_64
        dest=/usr/bin/RNAstemloop
        state=link
