---
# This playbook deploys miRkwood
- hosts: all
  sudo: True
  roles:
    - bioinfo
    - mirkwood
  tasks:
    - name: Create results directory
      file:
        path=/home/vagrant/results
        state=directory
        owner=www-data  
        group=www-data

    - name: Prepare results directory
      file:
        src=/home/vagrant/results
        dest=/mirkwood-results
        state=link

    - name: Making appropriate links
      file:
        src=/vagrant/
        dest=/mirkwood
        state=link

