--- 
# Deploys the miRkwood third-party program dependencies

- include: vienna-rna.yml

- name: Ensure build-essential is available
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - build-essential

- name: Install NCBI Blast+
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - ncbi-blast+
    
- name: Install bedtools
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - bedtools    

- name: Check if miRdup is installed
  stat:
    path=/opt/miRdup/miRdup.jar
    follow=true
  register: miRdup

- include: mirdup.yml
  when: miRdup.stat.exists == false

- name: Check if VARNA is installed
  stat:
    path=/opt/VARNAv3-91.jar
    follow=true
  register: varna

- include: varna.yml
  when: varna.stat.exists == false

- name: Check if tRNAscan-SE is installed
  stat:
    path=/opt/tRNAscan-SE/
    follow=true
  register: trnascanse

- include: trnascanse.yml
  when: trnascanse.stat.exists == false

- name: Check if RNAmmer is installed
  stat:
    path=/opt/RNAmmer/rnammer
    follow=true
  register: rnammer

- include: rnammer.yml
  when: rnammer.stat.exists == false

- name: Check if RNAshuffles is installed
  stat:
    path=/opt/rnashuffles
    follow=true
  register: rnashuffles

- include: rnashuffles.yml
  when: rnashuffles.stat.exists == false

- name: Install pandoc
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - pandoc
    - texlive
