---
- name: Copy miRdup archive
  copy:
    src: miRdup_1.4.zip
    dest: /tmp/miRdup_1.4.zip

- name: Ensure unzip is installed
  apt: pkg=unzip state=present

- name: Extract miRdup
  command: unzip -qq /tmp/miRdup_1.4.zip -d /opt/miRdup
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"


