---
# file: varna.yml

- name: Ensure the Java Runtime Environment is installed
  apt: pkg=default-jre state=present

- name: Download VARNA JAR
  get_url:
    dest=/opt/VARNAv3-91.jar
    url=http://varna.lri.fr/bin/VARNAv3-91.jar


