---
- name: Copy ViennaRNA Package 2.1.6 to remote
  copy: 
    src: vienna-rna_2.1.6-1_amd64.deb
    dest: /tmp/vienna-rna_2.1.6-1_amd64.deb

- name: Ensure ViennaRNA Package 2.1.6 is installed
  apt: deb=/tmp/vienna-rna_2.1.6-1_amd64.deb

- name: Install b2ct
  file:
    src=/usr/share/ViennaRNA/bin/b2ct
    dest=/usr/bin/b2ct
    state=link

